sudo: required

language: python
python:
  - "3.4"
  - "3.5"

services:
  - docker

before_install:
  - docker pull ubuntu:xenial
  - cd build && ./build.sh surok_image
  - ./build.sh alpine
  - ./build.sh centos
  - ./build.sh centos_rpm

script:
  - ./runtests.sh
